lista = ('Corinthians', 'Palmeiras', 'Santos', 'Grêmio', 'Cruzeiro', 'Flamengo', 'Vasco', 'Chapecoense', 'Atlético', 'Botafogo', 'Atlético-PR', 'Bahia', 'São paulo', 'Fluminense', 'Sport Recife', 'EC Vitória', 'Coritiba', 'Avaí', 'Ponte Preta', 'Atlético -GO')
pri = lista[0:5]
ult = lista[-4:]
organizado = sorted(lista)
chap = (lista[7])
print('-=' * 20)
print(f'Lista de times do Brasileirão: {lista}')
print('-=' * 20)
print(f'Os 5 primeiros são {pri}')
print('-=' * 20)
print(f'Os 4 últimos são {ult}')
print('-=' * 20)
print(f'Times em ordem alfabética: {organizado} ')
print('-=' * 20)
print(f'O Chapecoense está na {lista.index("Chapecoense")+1}ª posição')
